name: Install-PSModuleHelpers
description: Installs the PSModule helpers.
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  Debug:
    description: Enable debug output.
    required: false
    default: 'false'
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'false'
  Version:
    description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
    required: false
  Prerelease:
    description: Allow prerelease versions if available.
    required: false
    default: 'false'
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Install-PSModuleHelpers
      uses: PSModule/GitHub-Script@v1
      with:
        Debug: ${{ inputs.Debug }}
        Prerelease: ${{ inputs.Prerelease }}
        Verbose: ${{ inputs.Verbose }}
        Version: ${{ inputs.Version }}
        WorkingDirectory: ${{ inputs.WorkingDirectory }}
        Script: |
          # Install-PSModuleHelpers
          ${{ github.action_path }}/scripts/main.ps1
